Repository NBCAMP-EZPZ/EZPZ-Host, pull requests merged in 2024-08, with the labels that each got.

#29 Feat [#28] : 팝업 리뷰 개수, 평균 평점 컬럼 추가
  src/main/java/com/sparta/ezpzhost/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/popup/PopupRepositoryCustom.java
Labels: feat ✨

#44 Feat/statistics
  build.gradle
  src/main/java/com/sparta/ezpzhost/common/aop/LogAspect.java
  src/main/java/com/sparta/ezpzhost/common/config/BatchConfig.java
  src/main/java/com/sparta/ezpzhost/common/config/JobConfig.java
  src/main/java/com/sparta/ezpzhost/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzhost/common/scheduler/BatchScheduler.java
  src/main/java/com/sparta/ezpzhost/common/scheduler/PopupStatusScheduler.java
  src/main/java/com/sparta/ezpzhost/domain/item/repository/ItemRepository.java
  src/main/java/com/sparta/ezpzhost/domain/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/ezpzhost/domain/order/service/OrderService.java
  src/main/java/com/sparta/ezpzhost/domain/orderline/dto/OrderlineResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/orderline/repository/OrderlineRepository.java
  src/main/java/com/sparta/ezpzhost/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/popup/PopupRepository.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/controller/SalesStatisticsController.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/dto/DailyPopupSalesStatisticsResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/dto/MonthlySalesStatisticsResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/entity/DailyPopupSalesStatistics.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/entity/MonthlySalesStatistics.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/repository/DailyPopupSalesStatisticsRepository.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/repository/MonthlySalesStatisticsRepository.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/service/SalesStatisticsService.java
  src/main/resources/application.yml
Labels: feat ✨

#33 Feat/distributed lock
  src/main/java/com/sparta/ezpzhost/domain/host/entity/Host.java
  src/main/java/com/sparta/ezpzhost/domain/item/service/ItemService.java
  src/main/java/com/sparta/ezpzhost/domain/order/service/OrderService.java
  src/main/java/com/sparta/ezpzhost/domain/popup/controller/PopupController.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/PopupResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzhost/domain/popup/service/ImageService.java
  src/main/java/com/sparta/ezpzhost/domain/popup/service/PopupService.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotCreateDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotRequestDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/entity/Slot.java
  src/main/java/com/sparta/ezpzhost/domain/slot/repository/SlotRepository.java
  src/main/java/com/sparta/ezpzhost/domain/slot/service/SlotService.java
  src/test/java/com/sparta/ezpzhost/domain/order/service/OrderServiceTest.java
  src/test/java/com/sparta/ezpzhost/domain/slot/service/SlotConcurrencyTest.java
  src/test/java/com/sparta/ezpzhost/domain/slot/service/SlotServiceTest.java
  src/test/resources/application.yml
Labels: feat ✨, test 🧨

#46 Refactor/item
  src/main/java/com/sparta/ezpzhost/domain/item/entity/Item.java
  src/main/java/com/sparta/ezpzhost/domain/item/repository/ItemRepository.java
  src/main/java/com/sparta/ezpzhost/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzhost/domain/item/service/ItemService.java
  src/main/java/com/sparta/ezpzhost/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzhost/domain/order/service/OrderService.java
  src/main/java/com/sparta/ezpzhost/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/service/SalesStatisticsService.java
  src/test/java/com/sparta/ezpzhost/domain/order/service/OrderServiceTest.java
  src/test/java/com/sparta/ezpzhost/domain/slot/service/SlotConcurrencyTest.java
  src/test/java/com/sparta/ezpzhost/domain/slot/service/SlotServiceTest.java
Labels: refactor 🔧

#47 Refactor/statistics
  src/main/java/com/sparta/ezpzhost/common/config/JobConfig.java
  src/main/java/com/sparta/ezpzhost/common/config/batch/BatchConfig.java
  src/main/java/com/sparta/ezpzhost/common/config/batch/DailyPopupSalesJobConfig.java
  src/main/java/com/sparta/ezpzhost/common/config/batch/MonthlyItemSalesJobConfig.java
  src/main/java/com/sparta/ezpzhost/common/scheduler/BatchScheduler.java
  src/main/java/com/sparta/ezpzhost/common/scheduler/DailyPopupSalesScheduler.java
  src/main/java/com/sparta/ezpzhost/common/scheduler/MonthlyItemSalesScheduler.java
  src/main/java/com/sparta/ezpzhost/common/scheduler/PopupStatusScheduler.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/controller/SalesStatisticsController.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/dto/MonthlyItemSalesStatisticsResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/entity/MonthlyItemSalesStatistics.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/repository/MonthlyItemSalesStatisticsRepository.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/repository/MonthlySalesStatisticsRepository.java
  src/main/java/com/sparta/ezpzhost/domain/salesStatistics/service/SalesStatisticsService.java
Labels: refactor 🔧
