Repository NBCAMP-EZPZ/EZPZ-Host, pull requests merged in 2024-07, with the labels that each got.

#7 Feat/팝업
  build.gradle
  http/host.http
  http/http-client.env.json
  http/images/image.png
  http/popup.http
  src/main/java/com/sparta/ezpzhost/EzpzHostApplication.java
  src/main/java/com/sparta/ezpzhost/common/config/S3Config.java
  src/main/java/com/sparta/ezpzhost/common/entity/Timestamped.java
  src/main/java/com/sparta/ezpzhost/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzhost/common/util/PageUtil.java
  src/main/java/com/sparta/ezpzhost/domain/host/entity/Host.java
  src/main/java/com/sparta/ezpzhost/domain/popup/controller/PopupController.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/ImageResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/PopupPageResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/PopupRequestDto.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/PopupResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/popup/entity/Image.java
  src/main/java/com/sparta/ezpzhost/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzhost/domain/popup/enums/ApprovalStatus.java
  src/main/java/com/sparta/ezpzhost/domain/popup/enums/ImageType.java
  src/main/java/com/sparta/ezpzhost/domain/popup/enums/PopupStatus.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/ImageRepository.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/popup/PopupRepository.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/popup/PopupRepositoryCustom.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzhost/domain/popup/service/ImageService.java
  src/main/java/com/sparta/ezpzhost/domain/popup/service/PopupService.java
  src/main/java/com/sparta/ezpzhost/domain/popup/util/S3Util.java
  src/main/resources/application.yml
Labels: feat ✨, P0

#6 Feat/예약 정보 등록 기능
  src/main/java/com/sparta/ezpzhost/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzhost/domain/host/entity/Host.java
  src/main/java/com/sparta/ezpzhost/domain/popup/enums/ApprovalStatus.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/PopupRepository.java
  src/main/java/com/sparta/ezpzhost/domain/slot/controller/SlotController.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotCreateDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotRequestDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/entity/Slot.java
  src/main/java/com/sparta/ezpzhost/domain/slot/enums/SlotStatus.java
  src/main/java/com/sparta/ezpzhost/domain/slot/repository/SlotRepository.java
  src/main/java/com/sparta/ezpzhost/domain/slot/service/SlotService.java
Labels: feat ✨, P0

#15 Feat [#14] : 페이지네이션 기능, 예외 처리 구현
  src/main/java/com/sparta/ezpzhost/common/config/PageConfig.java
  src/main/java/com/sparta/ezpzhost/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzhost/common/resolver/CustomPageableHandlerMethodArgumentResolver.java
  src/main/java/com/sparta/ezpzhost/common/util/PageUtil.java
  src/main/java/com/sparta/ezpzhost/common/util/RepositoryUtil.java
Labels: feat ✨

#12 Feat/예약 조회
  src/main/java/com/sparta/ezpzhost/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/PopupRepository.java
  src/main/java/com/sparta/ezpzhost/domain/reservation/dto/ReservationListDto.java
  src/main/java/com/sparta/ezpzhost/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/ezpzhost/domain/reservation/enums/ReservationStatus.java
  src/main/java/com/sparta/ezpzhost/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/ezpzhost/domain/slot/controller/SlotController.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotResponseListDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/repository/SlotRepository.java
  src/main/java/com/sparta/ezpzhost/domain/slot/service/SlotService.java
  src/main/java/com/sparta/ezpzhost/domain/user/entity/User.java
Labels: feat ✨, P0

#16 Feat/굿즈
  http/item.http
  http/popup.http
  src/main/java/com/sparta/ezpzhost/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzhost/common/util/S3Util.java
  src/main/java/com/sparta/ezpzhost/domain/item/controller/ItemController.java
  src/main/java/com/sparta/ezpzhost/domain/item/dto/ItemCondition.java
  src/main/java/com/sparta/ezpzhost/domain/item/dto/ItemPageResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/item/dto/ItemRequestDto.java
  src/main/java/com/sparta/ezpzhost/domain/item/dto/ItemResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/item/entity/Item.java
  src/main/java/com/sparta/ezpzhost/domain/item/enums/ItemStatus.java
  src/main/java/com/sparta/ezpzhost/domain/item/repository/ItemRepository.java
  src/main/java/com/sparta/ezpzhost/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/sparta/ezpzhost/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzhost/domain/item/service/ItemService.java
  src/main/java/com/sparta/ezpzhost/domain/popup/controller/PopupController.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/ImageResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/PopupCondition.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/PopupPageResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/popup/dto/PopupResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/popup/PopupRepositoryCustom.java
  src/main/java/com/sparta/ezpzhost/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzhost/domain/popup/service/ImageService.java
  src/main/java/com/sparta/ezpzhost/domain/popup/service/PopupService.java
  src/main/java/com/sparta/ezpzhost/domain/slot/service/SlotService.java
Labels: feat ✨

#19 Feat/reservation (예약 수정, 삭제)
  src/main/java/com/sparta/ezpzhost/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzhost/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/ezpzhost/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/sparta/ezpzhost/domain/reservation/repository/ReservationRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzhost/domain/slot/controller/SlotController.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotUpdateDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/entity/Slot.java
  src/main/java/com/sparta/ezpzhost/domain/slot/repository/SlotRepository.java
  src/main/java/com/sparta/ezpzhost/domain/slot/repository/SlotRepositoryCustom.java
  src/main/java/com/sparta/ezpzhost/domain/slot/repository/SlotRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzhost/domain/slot/service/SlotService.java
Labels: feat ✨, refactor 🔧, P2, P3

#24 refactor [#23] : AOP
  build.gradle
  src/main/java/com/sparta/ezpzhost/common/aop/LogAspect.java
  src/main/java/com/sparta/ezpzhost/domain/item/repository/ItemRepositoryCustomImpl.java
Labels: feat ✨

#22 Test/reservation
  src/main/java/com/sparta/ezpzhost/domain/host/dto/SignupRequestDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotRequestDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/dto/SlotUpdateDto.java
  src/main/java/com/sparta/ezpzhost/domain/slot/service/SlotService.java
  src/test/java/com/sparta/ezpzhost/domain/slot/service/SlotServiceTest.java
  src/test/resources/application.yml
Labels: test ❗

#26 Test/orders
  src/main/java/com/sparta/ezpzhost/domain/cart/entity/Cart.java
  src/main/java/com/sparta/ezpzhost/domain/host/entity/Host.java
  src/main/java/com/sparta/ezpzhost/domain/item/entity/Item.java
  src/main/java/com/sparta/ezpzhost/domain/order/dto/OrderFindAllResponseDto.java
  src/main/java/com/sparta/ezpzhost/domain/order/dto/OrderRequestDto.java
  src/main/java/com/sparta/ezpzhost/domain/order/entity/Order.java
  src/main/java/com/sparta/ezpzhost/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzhost/domain/user/entity/User.java
  src/test/java/com/sparta/ezpzhost/EzpzHostApplicationTest.java
  src/test/java/com/sparta/ezpzhost/domain/order/service/OrderServiceTest.java
Labels: P0, test ❗
